import { db } from "./drizzle";
import { Category, Subcategory, Product } from "./schema";
import { eq } from "drizzle-orm";

async function seed() {
  console.log("🌱 Seeding database...");

  // --- Create Categories ---
  const grocery = await db.insert(Category).values({
    name: "Grocery & Daily Needs",
  }).returning();

  const snacks = await db.insert(Category).values({
    name: "Snacks & Drinks",
  }).returning();

  // --- Create Subcategories ---
  const rice = await db.insert(Subcategory).values({
    name: "Atta, Rice & Grains",
    categoryId: grocery[0].id,
  }).returning();

  const chips = await db.insert(Subcategory).values({
    name: "Chips & Namkeen",
    categoryId: snacks[0].id,
  }).returning();

  // --- Create Products ---
  await db.insert(Product).values([
    {
      name: "Basmati Rice Premium",
      price: "₹180/kg",
      originalPrice: "₹200/kg",
      categoryId: grocery[0].id,
      subcategoryId: rice[0].id,
      image: "https://images.pexels.com/photos/723198/pexels-photo-723198.jpeg?auto=compress&cs=tinysrgb&w=600",
      description: "Long grain aromatic basmati rice. Perfect for biryanis and pulao.",
      detailedDescription: "Premium quality basmati rice with extra-long grains and distinctive aroma.",
      brand: "India Gate",
      weight: "1kg",
      ingredients: "100% Pure Basmati Rice",
    },
    {
      name: "Lays Classic Salted",
      price: "₹20",
      originalPrice: "₹25",
      categoryId: snacks[0].id,
      subcategoryId: chips[0].id,
      image: "https://images.pexels.com/photos/4109236/pexels-photo-4109236.jpeg?auto=compress&cs=tinysrgb&w=600",
      description: "Crispy potato chips with classic salted flavor.",
      detailedDescription: "Lays Classic Salted chips made from quality potatoes and lightly salted.",
      brand: "Lays",
      weight: "52g",
      ingredients: "Potatoes, Edible Vegetable Oil, Salt",
    },
    {
      name: "Lays Classic Salted",
      price: "₹20",
      originalPrice: "₹25",
      categoryId: snacks[0].id,
      subcategoryId: chips[0].id,
      image: "https://images.pexels.com/photos/4109236/pexels-photo-4109236.jpeg?auto=compress&cs=tinysrgb&w=600",
      description: "Crispy potato chips with classic salted flavor.",
      detailedDescription: "Lays Classic Salted chips made from quality potatoes and lightly salted.",
      brand: "Lays",
      weight: "53g",
      ingredients: "Potatoes, Edible Vegetable Oil, Salt",
    },
    {
      name: "Lays Classic Salted",
      price: "₹20",
      originalPrice: "₹25",
      categoryId: snacks[0].id,
      subcategoryId: chips[0].id,
      image: "https://images.pexels.com/photos/4109236/pexels-photo-4109236.jpeg?auto=compress&cs=tinysrgb&w=600",
      description: "Crispy potato chips with classic salted flavor.",
      detailedDescription: "Lays Classic Salted chips made from quality potatoes and lightly salted.",
      brand: "Lays",
      weight: "54g",
      ingredients: "Potatoes, Edible Vegetable Oil, Salt",
    },
    {
      name: "Lays Classic Salted",
      price: "₹20",
      originalPrice: "₹25",
      categoryId: snacks[0].id,
      subcategoryId: chips[0].id,
      image: "https://images.pexels.com/photos/4109236/pexels-photo-4109236.jpeg?auto=compress&cs=tinysrgb&w=600",
      description: "Crispy potato chips with classic salted flavor.",
      detailedDescription: "Lays Classic Salted chips made from quality potatoes and lightly salted.",
      brand: "Lays",
      weight: "55g",
      ingredients: "Potatoes, Edible Vegetable Oil, Salt",
    },
    {
      name: "Lays Classic Salted",
      price: "₹20",
      originalPrice: "₹25",
      categoryId: snacks[0].id,
      subcategoryId: chips[0].id,
      image: "https://images.pexels.com/photos/4109236/pexels-photo-4109236.jpeg?auto=compress&cs=tinysrgb&w=600",
      description: "Crispy potato chips with classic salted flavor.",
      detailedDescription: "Lays Classic Salted chips made from quality potatoes and lightly salted.",
      brand: "Lays",
      weight: "32g",
      ingredients: "Potatoes, Edible Vegetable Oil, Salt",
    },
    {
      name: "Lays Classic Salted",
      price: "₹20",
      originalPrice: "₹25",
      categoryId: snacks[0].id,
      subcategoryId: chips[0].id,
      image: "https://images.pexels.com/photos/4109236/pexels-photo-4109236.jpeg?auto=compress&cs=tinysrgb&w=600",
      description: "Crispy potato chips with classic salted flavor.",
      detailedDescription: "Lays Classic Salted chips made from quality potatoes and lightly salted.",
      brand: "Lays",
      weight: "92g",
      ingredients: "Potatoes, Edible Vegetable Oil, Salt",
    },
    {
      name: "Lays Classic Salted",
      price: "₹20",
      originalPrice: "₹25",
      categoryId: snacks[0].id,
      subcategoryId: chips[0].id,
      image: "https://images.pexels.com/photos/4109236/pexels-photo-4109236.jpeg?auto=compress&cs=tinysrgb&w=600",
      description: "Crispy potato chips with classic salted flavor.",
      detailedDescription: "Lays Classic Salted chips made from quality potatoes and lightly salted.",
      brand: "Lays",
      weight: "62g",
      ingredients: "Potatoes, Edible Vegetable Oil, Salt",
    },
    {
      name: "Lays Classic Salted",
      price: "₹20",
      originalPrice: "₹25",
      categoryId: snacks[0].id,
      subcategoryId: chips[0].id,
      image: "https://images.pexels.com/photos/4109236/pexels-photo-4109236.jpeg?auto=compress&cs=tinysrgb&w=600",
      description: "Crispy potato chips with classic salted flavor.",
      detailedDescription: "Lays Classic Salted chips made from quality potatoes and lightly salted.",
      brand: "Lays",
      weight: "57g",
      ingredients: "Potatoes, Edible Vegetable Oil, Salt",
    },
    {
      name: "Lays Classic Salted",
      price: "₹20",
      originalPrice: "₹25",
      categoryId: snacks[0].id,
      subcategoryId: chips[0].id,
      image: "https://images.pexels.com/photos/4109236/pexels-photo-4109236.jpeg?auto=compress&cs=tinysrgb&w=600",
      description: "Crispy potato chips with classic salted flavor.",
      detailedDescription: "Lays Classic Salted chips made from quality potatoes and lightly salted.",
      brand: "Lays",
      weight: "5g",
      ingredients: "Potatoes, Edible Vegetable Oil, Salt",
    },
    {
      name: "Lays Classic Salted",
      price: "₹20",
      originalPrice: "₹25",
      categoryId: snacks[0].id,
      subcategoryId: chips[0].id,
      image: "https://images.pexels.com/photos/4109236/pexels-photo-4109236.jpeg?auto=compress&cs=tinysrgb&w=600",
      description: "Crispy potato chips with classic salted flavor.",
      detailedDescription: "Lays Classic Salted chips made from quality potatoes and lightly salted.",
      brand: "Lays",
      weight: "02g",
      ingredients: "Potatoes, Edible Vegetable Oil, Salt",
    },
    {
      name: "Lays Classic Salted",
      price: "₹20",
      originalPrice: "₹25",
      categoryId: snacks[0].id,
      subcategoryId: chips[0].id,
      image: "https://images.pexels.com/photos/4109236/pexels-photo-4109236.jpeg?auto=compress&cs=tinysrgb&w=600",
      description: "Crispy potato chips with classic salted flavor.",
      detailedDescription: "Lays Classic Salted chips made from quality potatoes and lightly salted.",
      brand: "Lays",
      weight: "51g",
      ingredients: "Potatoes, Edible Vegetable Oil, Salt",
    },
    {
      name: "Lays Classic Salted",
      price: "₹20",
      originalPrice: "₹25",
      categoryId: snacks[0].id,
      subcategoryId: chips[0].id,
      image: "https://images.pexels.com/photos/4109236/pexels-photo-4109236.jpeg?auto=compress&cs=tinysrgb&w=600",
      description: "Crispy potato chips with classic salted flavor.",
      detailedDescription: "Lays Classic Salted chips made from quality potatoes and lightly salted.",
      brand: "Lays",
      weight: "98g",
      ingredients: "Potatoes, Edible Vegetable Oil, Salt",
    },
    {
      name: "Lays Classic Salted",
      price: "₹20",
      originalPrice: "₹25",
      categoryId: snacks[0].id,
      subcategoryId: chips[0].id,
      image: "https://images.pexels.com/photos/4109236/pexels-photo-4109236.jpeg?auto=compress&cs=tinysrgb&w=600",
      description: "Crispy potato chips with classic salted flavor.",
      detailedDescription: "Lays Classic Salted chips made from quality potatoes and lightly salted.",
      brand: "Lays",
      weight: "2438g",
      ingredients: "Potatoes, Edible Vegetable Oil, Salt",
    },
    {
      name: "Lays Classic Salted",
      price: "₹20",
      originalPrice: "₹25",
      categoryId: snacks[0].id,
      subcategoryId: chips[0].id,
      image: "https://images.pexels.com/photos/4109236/pexels-photo-4109236.jpeg?auto=compress&cs=tinysrgb&w=600",
      description: "Crispy potato chips with classic salted flavor.",
      detailedDescription: "Lays Classic Salted chips made from quality potatoes and lightly salted.",
      brand: "Lays",
      weight: "34g",
      ingredients: "Potatoes, Edible Vegetable Oil, Salt",
    },
    {
      name: "Lays Classic Salted",
      price: "₹20",
      originalPrice: "₹25",
      categoryId: snacks[0].id,
      subcategoryId: chips[0].id,
      image: "https://images.pexels.com/photos/4109236/pexels-photo-4109236.jpeg?auto=compress&cs=tinysrgb&w=600",
      description: "Crispy potato chips with classic salted flavor.",
      detailedDescription: "Lays Classic Salted chips made from quality potatoes and lightly salted.",
      brand: "Lays",
      weight: "59Kg",
      ingredients: "Potatoes, Edible Vegetable Oil, Salt",
    },
    {
      name: "Lays Classic Salted",
      price: "₹20",
      originalPrice: "₹25",
      categoryId: snacks[0].id,
      subcategoryId: chips[0].id,
      image: "https://images.pexels.com/photos/4109236/pexels-photo-4109236.jpeg?auto=compress&cs=tinysrgb&w=600",
      description: "Crispy potato chips with classic salted flavor.",
      detailedDescription: "Lays Classic Salted chips made from quality potatoes and lightly salted.",
      brand: "Lays",
      weight: "52hg",
      ingredients: "Potatoes, Edible Vegetable Oil, Salt",
    },
    {
      name: "Lays Classic Salted",
      price: "₹20",
      originalPrice: "₹25",
      categoryId: snacks[0].id,
      subcategoryId: chips[0].id,
      image: "https://images.pexels.com/photos/4109236/pexels-photo-4109236.jpeg?auto=compress&cs=tinysrgb&w=600",
      description: "Crispy potato chips with classic salted flavor.",
      detailedDescription: "Lays Classic Salted chips made from quality potatoes and lightly salted.",
      brand: "Lays",
      weight: "50lg",
      ingredients: "Potatoes, Edible Vegetable Oil, Salt",
    },
    {
      name: "Lays Classic Salted",
      price: "₹20",
      originalPrice: "₹25",
      categoryId: snacks[0].id,
      subcategoryId: chips[0].id,
      image: "https://images.pexels.com/photos/4109236/pexels-photo-4109236.jpeg?auto=compress&cs=tinysrgb&w=600",
      description: "Crispy potato chips with classic salted flavor.",
      detailedDescription: "Lays Classic Salted chips made from quality potatoes and lightly salted.",
      brand: "Lays",
      weight: "082g",
      ingredients: "Potatoes, Edible Vegetable Oil, Salt",
    },
    {
      name: "Lays Classic Salted",
      price: "₹20",
      originalPrice: "₹25",
      categoryId: snacks[0].id,
      subcategoryId: chips[0].id,
      image: "https://images.pexels.com/photos/4109236/pexels-photo-4109236.jpeg?auto=compress&cs=tinysrgb&w=600",
      description: "Crispy potato chips with classic salted flavor.",
      detailedDescription: "Lays Classic Salted chips made from quality potatoes and lightly salted.",
      brand: "Lays",
      weight: "22g",
      ingredients: "Potatoes, Edible Vegetable Oil, Salt",
    },
  ]);

  console.log("✅ Database seeded successfully!");
}

seed()
  .catch((err) => {
    console.error("❌ Error seeding database:", err);
  })
  .finally(() => process.exit(0));
